version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - mongo
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   links:
  #     - server
  mongo:
    image: mongo
    ports:
      - "27017:27017"